# Generated by Django on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_contact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
    ]
