# Generated by Django 5.2.13 on 2026-05-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_appointment_status_appointment_token_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('prescribed_for', models.CharField(blank=True, default='', max_length=100)),
                ('dosage_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='ward',
            field=models.CharField(blank=True, choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Emergency', 'Emergency'), ('Pediatrics', 'Pediatrics'), ('Maternity', 'Maternity'), ('Private Room', 'Private Room')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Blood Test', 'Blood Test'), ('Scan', 'Scan'), ('X-Ray', 'X-Ray'), ('Urine Test', 'Urine Test'), ('Other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('report_file', models.FileField(upload_to='reports/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing')], default='Ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.patient')),
            ],
        ),
    ]
